In [5]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Assume X, weights_input_hidden, weights_hidden_output, hidden_neurons, output_neurons are already defined

# Initialize biases randomly
bias_hidden = np.random.uniform(-1, 1, (1, hidden_neurons))
bias_output = np.random.uniform(-1, 1, (1, output_neurons))

# Forward Propagation
hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)

output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
output = sigmoid(output_layer_input)

print("Output after Forward Propagation:")
print(output)

Output after Forward Propagation:
[[0.99612501]
 [0.99644712]
 [0.99354137]
 [0.99184932]]


In [7]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Sigmoid derivative function for backpropagation
def sigmoid_derivative(x):
    return x * (1 - x)  # Corrected derivative

# XOR Input and Output
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])  # Input data
y = np.array([[0], [1], [1], [0]])              # Expected XOR output

# Neural Network structure
input_neurons = 2
hidden_neurons = 4
output_neurons = 1
learning_rate = 0.1
epochs = 10000

# Initialize weights and biases
np.random.seed(42)  # For reproducibility
weights_input_hidden = np.random.uniform(-1, 1, (input_neurons, hidden_neurons))
weights_hidden_output = np.random.uniform(-1, 1, (hidden_neurons, output_neurons))
bias_hidden = np.random.uniform(-1, 1, (1, hidden_neurons))
bias_output = np.random.uniform(-1, 1, (1, output_neurons))

# Training the neural network
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # Backpropagation
    output_error = y - predicted_output
    output_delta = output_error * sigmoid_derivative(predicted_output)

    hidden_layer_error = output_delta.dot(weights_hidden_output.T)
    hidden_layer_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weights_hidden_output += hidden_layer_output.T.dot(output_delta) * learning_rate
    bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
    weights_input_hidden += X.T.dot(hidden_layer_delta) * learning_rate
    bias_hidden += np.sum(hidden_layer_delta, axis=0, keepdims=True) * learning_rate

    # Print cost every 1000 epochs
    if (epoch + 1) % 1000 == 0:
        cost = np.mean(np.square(output_error))
        print(f"Epoch {epoch + 1}, Cost: {cost:.4f}")

# Testing the trained network
hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
hidden_layer_output = sigmoid(hidden_layer_input)
output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
predicted_output = sigmoid(output_layer_input)

print("\nPredicted Output after Training:")
print(predicted_output)

# Round the output for classification
rounded_output = np.round(predicted_output)
print("\nRounded Output (Classification):")
print(rounded_output)

Epoch 1000, Cost: 0.2392
Epoch 2000, Cost: 0.1510
Epoch 3000, Cost: 0.0287
Epoch 4000, Cost: 0.0109
Epoch 5000, Cost: 0.0062
Epoch 6000, Cost: 0.0043
Epoch 7000, Cost: 0.0032
Epoch 8000, Cost: 0.0025
Epoch 9000, Cost: 0.0021
Epoch 10000, Cost: 0.0018

Predicted Output after Training:
[[0.04490647]
 [0.95965947]
 [0.95728801]
 [0.04008788]]

Rounded Output (Classification):
[[0.]
 [1.]
 [1.]
 [0.]]
